name: "Netlify Deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8.8.0'
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - uses: veloii/action-netlify-deploy@v2.2.1
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref_name }}"